services:
  db:
    image: mysql:8.0
    container_name: updevic-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: updevic
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  app:
    image: "aydanrahimova/updevic"
    container_name: updevic-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/your_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - updevic

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - updevic


networks:
  updevic:
    driver: "bridge"