spring:
  application:
    name: UpDevic_001
  datasource:
    url: jdbc:mysql://localhost:3306/start-up
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
      org.springframework.data.jpa.repository: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: lgwc ajdp xxjj cyuq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      expiration: 86400000
      key: ${SECURITY_KEY}

  secret:
    key: ${KEY}

ALGORITHM: ${ALGORITHM}
#
##java:
##  io:
##    tmpdir=C:/TEMP:
#server:
#  tomcat:
#    basedir: C:/Users/Asus/AppData/Local/Temp
#
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


server:
  tomcat:
    uri-encoding: utf-8

video:
  directory: D://Videos/