spring:
  application:
    name: UpDevic_001
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
        org.springframework.data.jpa.repository: DEBUG


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      expiration: 900000
      key: ${SECURITY_KEY}


email:
  fromEmail: ${FROM_EMAIL}

ALGORITHM: ${ALGORITHM}



#
##java:
##  io:
##    tmpdir=C:/TEMP:
#server:
#  tomcat:
#    basedir: C:/Users/Asus/AppData/Local/Temp
#
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
